import os
import sys
import re
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle, Image, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont('Nirmala', 8.5)
        self.setFillColor(colors.HexColor('#4B5563'))
        
        # Footer text
        footer_text = "📚 Generated by A/L MCQ HUB AI Tutor  |  Telegram: @AL_MCQbot"
        page_str = f"Page {self._pageNumber} of {page_count}"
        
        self.drawString(36, 20, footer_text)
        self.drawRightString(A4[0] - 36, 20, page_str)
        
        # Footer Line
        self.setStrokeColor(colors.HexColor('#D1D5DB'))
        self.setLineWidth(0.8)
        self.line(36, 32, A4[0] - 36, 32)
        
        self.restoreState()

def sanitize_text_for_pdf(text):
    if not text:
        return ""
    
    t = text
    
    # 1. Clean LaTeX arrow expressions (e.g. \\(\rightarrow\\), \rightarrow, \implies)
    t = re.sub(r'\\\\?\(\s*\\?rightarrow\s*\\\\?\)', ' → ', t)
    t = re.sub(r'\\\\?\(\s*\\?implies\s*\\\\?\)', ' ⇒ ', t)
    t = re.sub(r'\\?rightarrow', ' → ', t)
    t = re.sub(r'\\?implies', ' ⇒ ', t)
    t = re.sub(r'\\\\?\([^\)]*\\\\?\)', '', t)
    
    # 2. Strip NotebookLM citation tags [1], [1, 2]
    t = re.sub(r'\[\d+(?:\s*,\s*\d+|-?\d+)*\]', '', t)
    
    # 3. Clean up multiple spaces & trailing punctuation spaces
    t = re.sub(r'[ \t]{2,}', ' ', t)
    t = t.replace(' .', '.').replace(' ,', ',')
    
    # 4. Remove emojis that break font rendering (e.g. 📌, 👉, 🇱🇰, ☸️, 🏛️, ⚖️, 💼, 🤖, 💡, ⌛, 📄, 🏆)
    t = re.sub(r'[\U00010000-\U0010ffff]', '', t)
    t = re.sub(r'[\u2600-\u27BF]', '', t)
    t = re.sub(r'[\u2300-\u23FF]', '', t)

    # 5. Convert Markdown bold **text** or __text__ to <b>text</b>
    t = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', t)
    t = re.sub(r'__(.*?)__', r'<b>\1</b>', t)

    # 6. Convert Markdown italic *text* to <i>text</i>
    t = re.sub(r'(?<!\w)\*([^\*\n]+)\*(?!\w)', r'<i>\1</i>', t)

    # 7. Protect existing valid HTML tags <b>, </b>, <i>, </i> from XML escaping
    t = t.replace('<b>', '___B_OPEN___').replace('</b>', '___B_CLOSE___')
    t = t.replace('<i>', '___I_OPEN___').replace('</i>', '___I_CLOSE___')
    
    # Escape XML special characters (&, <, >)
    t = t.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    
    # Restore HTML tags
    t = t.replace('___B_OPEN___', '<b>').replace('___B_CLOSE___', '</b>')
    t = t.replace('___I_OPEN___', '<i>').replace('___I_CLOSE___', '</i>')

    return t.strip()

def generate_pdf_study_note(topic_title, raw_content, output_path):
    # Register Sinhala TTF Font
    font_path = 'C:/Windows/Fonts/NIRMALA.TTF'
    if not os.path.exists(font_path):
        font_path = 'C:/Windows/Fonts/NIRMALA.TTC'
    
    pdfmetrics.registerFont(TTFont('Nirmala', font_path))
    
    # Document Setup
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=36,
        rightMargin=36,
        topMargin=32,
        bottomMargin=42
    )
    
    styles = getSampleStyleSheet()
    
    total_width = A4[0] - 72  # 523.27 pt

    # Custom Paragraph Styles
    brand_title_style = ParagraphStyle(
        'BrandTitle',
        parent=styles['Normal'],
        fontName='Nirmala',
        fontSize=15,
        leading=19,
        textColor=colors.HexColor('#FFFFFF')
    )

    brand_subtitle_style = ParagraphStyle(
        'BrandSubtitle',
        parent=styles['Normal'],
        fontName='Nirmala',
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor('#93C5FD')
    )

    header_meta_style = ParagraphStyle(
        'HeaderMeta',
        parent=styles['Normal'],
        fontName='Nirmala',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#E0E7FF'),
        alignment=2 # Right
    )

    section_heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading1'],
        fontName='Nirmala',
        fontSize=11.5,
        leading=15.5,
        textColor=colors.HexColor('#1E40AF')
    )

    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['Normal'],
        fontName='Nirmala',
        fontSize=10,
        leading=15,
        textColor=colors.HexColor('#1F2937'),
        spaceAfter=5
    )

    bullet_style = ParagraphStyle(
        'BulletStyle',
        parent=body_style,
        leftIndent=12,
        firstLineIndent=-8,
        spaceAfter=4
    )

    sub_bullet_style = ParagraphStyle(
        'SubBulletStyle',
        parent=body_style,
        leftIndent=24,
        firstLineIndent=-8,
        spaceAfter=3
    )

    example_text_style = ParagraphStyle(
        'ExampleTextStyle',
        parent=body_style,
        fontSize=9.5,
        leading=14,
        textColor=colors.HexColor('#065F46'),
        spaceAfter=3
    )

    story = []

    # 1. Header Banner Box with Logo
    logo_file = None
    possible_logos = [
        'our_logo.png',
        'c:/bak/projects/AL BC/A-L-main/our_logo.png',
        'logo.png',
        'c:/bak/projects/AL BC/A-L-main/logo.png'
    ]
    for lp in possible_logos:
        if os.path.exists(lp):
            logo_file = lp
            break

    clean_topic = sanitize_text_for_pdf(topic_title) or "උසස් පෙළ අධ්‍යයන සටහන"
    date_str = datetime.now().strftime('%Y-%m-%d')

    if logo_file:
        logo_img = Image(logo_file, width=46, height=46)
        title_para = Paragraph("<b>A/L MCQ HUB AI TUTOR</b> — STUDY GUIDE", brand_title_style)
        sub_para = Paragraph("උසස් පෙළ විෂය කරුණු සහ අධ්‍යයන සටහන (G.C.E. A/L Study Note)", brand_subtitle_style)
        meta_para = Paragraph(f"<b>මාතෘකාව:</b> {clean_topic}<br/>🗓️ {date_str}", header_meta_style)

        text_cell = [title_para, Spacer(1, 2), sub_para]
        header_table = Table([[logo_img, text_cell, meta_para]], colWidths=[52, 305, 166])
        header_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#1E3A8A')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ]))
        story.append(header_table)
    else:
        title_para = Paragraph("<b>A/L MCQ HUB AI TUTOR — STUDY GUIDE</b>", brand_title_style)
        meta_para = Paragraph(f"<b>මාතෘකාව:</b> {clean_topic} | 🗓️ {date_str}", brand_subtitle_style)
        header_table = Table([[title_para], [meta_para]], colWidths=[total_width])
        header_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#1E3A8A')),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ]))
        story.append(header_table)

    story.append(Spacer(1, 12))

    # 2. Process Content Lines
    lines = raw_content.split('\n')
    
    in_example_block = False
    example_lines = []

    def flush_example_block():
        nonlocal example_lines
        if not example_lines:
            return
        
        block_paras = [Paragraph(l, example_text_style) for l in example_lines]
        card_table = Table([[block_paras]], colWidths=[total_width])
        card_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F0FDF4')),
            ('LINELEFT', (0, 0), (-1, -1), 3.5, colors.HexColor('#10B981')),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ]))
        story.append(Spacer(1, 3))
        story.append(card_table)
        story.append(Spacer(1, 5))
        example_lines = []

    for line in lines:
        raw_line = line.strip()
        if not raw_line:
            if in_example_block:
                flush_example_block()
                in_example_block = False
            else:
                story.append(Spacer(1, 3))
            continue

        clean_l = sanitize_text_for_pdf(raw_line)
        if not clean_l:
            continue

        # Convert Headers (### or 📌) into Styled Pill Cards
        if raw_line.startswith('###') or raw_line.startswith('##') or raw_line.startswith('📌') or raw_line.startswith('#'):
            if in_example_block:
                flush_example_block()
                in_example_block = False

            title_text = re.sub(r'^[#📌\s*]+', '', clean_l).strip()
            if title_text:
                head_para = Paragraph(f"<b>📌 {title_text}</b>", section_heading_style)
                head_table = Table([[head_para]], colWidths=[total_width])
                head_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#EFF6FF')),
                    ('LINELEFT', (0, 0), (-1, -1), 4, colors.HexColor('#2563EB')),
                    ('TOPPADDING', (0, 0), (-1, -1), 5),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                    ('LEFTPADDING', (0, 0), (-1, -1), 8),
                    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
                ]))
                story.append(Spacer(1, 8))
                story.append(head_table)
                story.append(Spacer(1, 5))
            continue

        # Convert Horizontal Dividers (---, ___, ━━━━)
        if re.match(r'^[-\*_]{3,}$', raw_line) or '━━━━' in raw_line or '────' in raw_line:
            if in_example_block:
                flush_example_block()
                in_example_block = False
            story.append(HRFlowable(width="100%", thickness=0.8, color=colors.HexColor('#E5E7EB'), spaceBefore=5, spaceAfter=7))
            continue

        # Detect Examples / Callout Boxes (👉 or නිදසුන්: or උදාහරණ:)
        if '👉' in raw_line or 'නිදසුන්:' in raw_line or 'උදාහරණ:' in raw_line:
            in_example_block = True
            example_lines.append(clean_l)
            continue

        if in_example_block:
            if raw_line.startswith('•') or raw_line.startswith('*') or raw_line.startswith('-') or raw_line.startswith('▸'):
                example_lines.append(clean_l)
                continue
            else:
                flush_example_block()
                in_example_block = False

        # Convert Nested Sub-bullets (   ▸ or * *)
        if raw_line.startswith('▸') or raw_line.startswith('   ▸') or raw_line.startswith('* *') or raw_line.startswith('- -'):
            bullet_text = re.sub(r'^[▸\*\-\s]+', '', clean_l)
            story.append(Paragraph(f"▸ {bullet_text}", sub_bullet_style))
            continue

        # Convert Top-level Bullets (• or * or -)
        if raw_line.startswith('•') or raw_line.startswith('*') or raw_line.startswith('-'):
            bullet_text = re.sub(r'^[•\*\-\s]+', '', clean_l)
            story.append(Paragraph(f"• {bullet_text}", bullet_style))
            continue

        # Standard Body Paragraph
        story.append(Paragraph(clean_l, body_style))

    if in_example_block:
        flush_example_block()

    # Build Document with NumberedCanvas
    doc.build(story, canvasmaker=NumberedCanvas)
    return output_path

if __name__ == '__main__':
    if len(sys.argv) >= 4:
        title = sys.argv[1]
        text_file = sys.argv[2]
        out_pdf = sys.argv[3]
        
        with open(text_file, 'r', encoding='utf-8') as f:
            content = f.read()
            
        generate_pdf_study_note(title, content, out_pdf)
        print(f"SUCCESS: PDF created at {out_pdf}")
    else:
        print("Usage: python generate_pdf_note.py <topic_title> <text_file_path> <output_pdf_path>")
