import os
import sys
import re
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont('Nirmala', 9)
        self.setFillColor(colors.HexColor('#6B7280'))
        
        # Footer
        footer_text = "📚 Generated by A/L MCQ HUB AI Tutor  |  https://t.me/AL_MCQbot"
        page_str = f"Page {self._pageNumber} of {page_count}"
        
        self.drawString(36, 25, footer_text)
        self.drawRightString(A4[0] - 36, 25, page_str)
        
        # Footer Line
        self.setStrokeColor(colors.HexColor('#E5E7EB'))
        self.setLineWidth(0.8)
        self.line(36, 38, A4[0] - 36, 38)
        
        self.restoreState()

def clean_text_for_pdf(text):
    if not text:
        return ""
    # Strip citation tags like [1], [1, 2]
    clean = re.sub(r'\[\d+(?:\s*,\s*\d+|-?\d+)*\]', '', text)
    clean = re.sub(r'[ \t]{2,}', ' ', clean)
    clean = clean.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    return clean

def generate_pdf_study_note(topic_title, raw_content, output_path):
    # Register Sinhala Unicode TTF Font
    font_path = 'C:/Windows/Fonts/NIRMALA.TTF'
    if not os.path.exists(font_path):
        font_path = 'C:/Windows/Fonts/NIRMALA.TTC'
    
    pdfmetrics.registerFont(TTFont('Nirmala', font_path))
    
    # Document Setup
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=36,
        rightMargin=36,
        topMargin=40,
        bottomMargin=50
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Styles
    brand_header_style = ParagraphStyle(
        'BrandHeader',
        parent=styles['Normal'],
        fontName='Nirmala',
        fontSize=18,
        leading=22,
        textColor=colors.HexColor('#FFFFFF'),
        alignment=1  # Center
    )
    
    sub_brand_style = ParagraphStyle(
        'SubBrand',
        parent=styles['Normal'],
        fontName='Nirmala',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#E0E7FF'),
        alignment=1  # Center
    )

    h1_style = ParagraphStyle(
        'Heading1Style',
        parent=styles['Heading1'],
        fontName='Nirmala',
        fontSize=14,
        leading=19,
        textColor=colors.HexColor('#1E3A8A'),
        spaceBefore=14,
        spaceAfter=6,
        keepWithNext=True
    )

    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['Normal'],
        fontName='Nirmala',
        fontSize=10.5,
        leading=16,
        textColor=colors.HexColor('#1F2937'),
        spaceAfter=6
    )

    bullet_style = ParagraphStyle(
        'BulletStyle',
        parent=body_style,
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=5
    )

    sub_bullet_style = ParagraphStyle(
        'SubBulletStyle',
        parent=body_style,
        leftIndent=30,
        firstLineIndent=-10,
        spaceAfter=4
    )

    example_style = ParagraphStyle(
        'ExampleStyle',
        parent=body_style,
        leftIndent=20,
        textColor=colors.HexColor('#065F46'),
        spaceBefore=4,
        spaceAfter=6
    )

    story = []

    # 1. Header Banner Box
    header_data = [
        [Paragraph("🎓 <b>A/L MCQ HUB AI TUTOR — STUDY GUIDE</b>", brand_header_style)],
        [Paragraph(f"📌 <b>මාතෘකාව:</b> {clean_text_for_pdf(topic_title)} &nbsp;|&nbsp; 🗓️ {datetime.now().strftime('%Y-%m-%d')}", sub_brand_style)]
    ]
    header_table = Table(header_data, colWidths=[A4[0] - 72])
    header_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#1E3A8A')),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('CORNERPAD', (0, 0), (-1, -1), 4),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 15))

    # 2. Process Content Lines
    lines = raw_content.split('\n')
    
    for line in lines:
        raw_line = line.strip()
        if not raw_line:
            story.append(Spacer(1, 4))
            continue

        clean_l = clean_text_for_pdf(raw_line)
        
        # Convert Markdown Bold (**text** -> <b>text</b>)
        clean_l = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', clean_l)
        clean_l = re.sub(r'__(.*?)__', r'<b>\1</b>', clean_l)

        # Convert Headers (### or 📌)
        if raw_line.startswith('###') or raw_line.startswith('##') or raw_line.startswith('📌'):
            title_text = re.sub(r'^[#📌\s*]+', '', clean_l).strip()
            if title_text:
                story.append(Spacer(1, 8))
                story.append(Paragraph(f"📌 <b>{title_text}</b>", h1_style))
                story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#3B82F6'), spaceBefore=2, spaceAfter=8))
            continue

        # Convert Dividers (---, ___)
        if re.match(r'^[-\*_]{3,}$', raw_line) or '━━━━' in raw_line or '────' in raw_line:
            story.append(HRFlowable(width="100%", thickness=0.8, color=colors.HexColor('#E5E7EB'), spaceBefore=6, spaceAfter=8))
            continue

        # Convert Nested Sub-bullets (   ▸ or * *)
        if raw_line.startswith('▸') or raw_line.startswith('   ▸') or raw_line.startswith('* *') or raw_line.startswith('- -'):
            bullet_text = re.sub(r'^[▸\*\-\s]+', '', clean_l)
            story.append(Paragraph(f"▸ {bullet_text}", sub_bullet_style))
            continue

        # Convert Top-level Bullets (• or * or -)
        if raw_line.startswith('•') or raw_line.startswith('*') or raw_line.startswith('-'):
            bullet_text = re.sub(r'^[•\*\-\s]+', '', clean_l)
            story.append(Paragraph(f"• {bullet_text}", bullet_style))
            continue

        # Convert Examples / Callouts (👉)
        if '👉' in raw_line or 'නිදසුන්:' in raw_line or 'උදාහරණ:' in raw_line:
            story.append(Paragraph(clean_l, example_style))
            continue

        # Standard Body Paragraph
        story.append(Paragraph(clean_l, body_style))

    # Build Document with NumberedCanvas
    doc.build(story, canvasmaker=NumberedCanvas)
    return output_path

if __name__ == '__main__':
    if len(sys.argv) >= 4:
        title = sys.argv[1]
        text_file = sys.argv[2]
        out_pdf = sys.argv[3]
        
        with open(text_file, 'r', encoding='utf-8') as f:
            content = f.read()
            
        generate_pdf_study_note(title, content, out_pdf)
        print(f"SUCCESS: PDF created at {out_pdf}")
    else:
        print("Usage: python generate_pdf_note.py <topic_title> <text_file_path> <output_pdf_path>")
