name = "a-l"
main = "worker.js"
compatibility_date = "2026-07-31"

[vars]
BOT_TOKEN = "8463293577:AAF2N2_PIP1WIoZE32Q_RMTQ8l1vr_6uXfc"
ADMIN_ID = "2035260032"
GROUP_URL = "https://t.me/+wZUSJyEncD1mYjFl"
FB_PAGE_URL = "https://facebook.com/ALMSQHUB"
WA_CHANNEL_URL = "https://whatsapp.com/channel/0029VbDIx2lHwXb4rvJNIV0D"
BASE_URL = "https://dmadushanka.github.io/A-L"
